// Pulls the torn-paper ridge from the brochure covers (pages 4 and 2) so the site's edges match exactly.
// node scripts/extract-ridges.mjs <folder with p2.png and p4.png rendered at 400dpi>
import sharp from 'sharp'
import fs from 'node:fs'
import path from 'node:path'

const K = 400 / 90
const SAMPLES = 480
// [page, x0, x1, y0, y1] in 90dpi preview coordinates, spanning the green block's torn top edge
const EDGES = [
  [4, 386, 716, 340, 470],
  [2, 725, 1055, 330, 460],
]

const ridges = []
for (const [page, x0, x1, y0, y1] of EDGES) {
  const W = Math.round((x1 - x0) * K), H = Math.round((y1 - y0) * K)
  const { data, info } = await sharp(path.join(process.argv[2], `p${page}.png`))
    .extract({ left: Math.round(x0 * K), top: Math.round(y0 * K), width: W, height: H })
    .raw().toBuffer({ resolveWithObject: true })
  const raw = []
  for (let x = 0; x < W; x++) {
    let edge = H
    for (let y = 0; y < H; y++) {
      const i = (y * W + x) * info.channels
      if (data[i + 1] - data[i] > 25 && data[i] < 120) { edge = y; break }
    }
    raw.push(edge)
  }
  const smooth = raw.map((_, i) => [...raw.slice(Math.max(0, i - 2), i + 3)].sort((a, b) => a - b)[2] ?? raw[i])
  const lo = Math.min(...smooth), hi = Math.max(...smooth)
  const out = []
  for (let s = 0; s < SAMPLES; s++) {
    const v = smooth[Math.round((s / (SAMPLES - 1)) * (W - 1))]
    out.push(Math.round(((v - lo) / (hi - lo)) * 1000) / 1000)
  }
  ridges.push(out)
  console.log(`page ${page}: ${W}px, relief ${hi - lo}px`)
}
fs.writeFileSync('src/art/ridges.js', '// Generated by scripts/extract-ridges.mjs from the brochure cover tears (0 = peak, 1 = trough).\n' + `export default ${JSON.stringify(ridges)}\n`)
